### PR TITLE
Added TTL to messages and refactored the room schema

### PR DESCRIPTION
**Pull request by dk222gs**
If you add a ttl directly to the message array it will probably not work.
This is why I refactored the message out to a separate schema and set the expires from there. 

Please test before merging PR.

### CODE REVIEW

**Comment by dk222gs** [comment]
DON'T MERGE THIS PR!

I did some testing and tried a couple of variants and all of them will expire the main schema which is `room`.
The current implementation will expire room with all messages after 10 sec. 

In order to make this work we need to refactor the DB structure so Message is using it's own schema and room is referring to messages via a messageId.

What do you guys think?

**Comment by dk222gs** [comment]
It looks like we have 3 alternatives:
1. Refactor DB, separate room and message.
2. Create a small db admin app that deletes all the messages from DB that are 30 days old. This app will run once a day with a Heroku plugin.
3. Just execute a loop that runs one/day in the webchat app that runs the same functionality as in nr2.

**Comment by ej222pj** [comment]
4 alternative, everytime messages are pulled, we check if they are over 30 days and remove them before they leave the server. 

What do you think?

**Comment by dk222gs** [comment]
@ej222pj  That is a good approach (A little bit late, I know :) )

**Pull request closed without merging**
